export const ACCENT_TYPES = [
  'american',
  'british',
  'australian',
  'canadian',
  'irish',
  'scottish',
  'parisian',
  'quebecois',
  'belgian',
  'swiss',
  'spanish',
  'latin',
  'greek',
  'mandarin',
  'hindi',
  'arabic',
  'bengali',
  'russian',
  'portuguese',
  'indonesian',
  'urdu',
  'german',
  'japanese',
  'nigerian-pidgin',
  'marathi',
  'telugu',
  'turkish',
  'tamil',
  'cantonese',
  'vietnamese',
] as const;

export type AccentType = (typeof ACCENT_TYPES)[number];

export const ACCENT_NAMES: Record<AccentType, { en: string; fr: string }> = {
  american: { en: 'American', fr: 'Américain' },
  british: { en: 'British', fr: 'Britannique' },
  australian: { en: 'Australian', fr: 'Australien' },
  canadian: { en: 'Canadian', fr: 'Canadien' },
  irish: { en: 'Irish', fr: 'Irlandais' },
  scottish: { en: 'Scottish', fr: 'Écossais' },
  parisian: { en: 'Parisian', fr: 'Parisien' },
  quebecois: { en: 'Québécois', fr: 'Québécois' },
  belgian: { en: 'Belgian', fr: 'Belge' },
  swiss: { en: 'Swiss', fr: 'Suisse' },
  spanish: { en: 'Spanish', fr: 'Espagnol' },
  latin: { en: 'Latin', fr: 'Latin' },
  greek: { en: 'Greek', fr: 'Grec' },
  mandarin: { en: 'Mandarin', fr: 'Mandarin' },
  hindi: { en: 'Hindi', fr: 'Hindi' },
  arabic: { en: 'Arabic', fr: 'Arabe' },
  bengali: { en: 'Bengali', fr: 'Bengali' },
  russian: { en: 'Russian', fr: 'Russe' },
  portuguese: { en: 'Portuguese', fr: 'Portugais' },
  indonesian: { en: 'Indonesian', fr: 'Indonésien' },
  urdu: { en: 'Urdu', fr: 'Ourdou' },
  german: { en: 'German', fr: 'Allemand' },
  japanese: { en: 'Japanese', fr: 'Japonais' },
  'nigerian-pidgin': { en: 'Nigerian Pidgin', fr: 'Pidgin nigérian' },
  marathi: { en: 'Marathi', fr: 'Marathi' },
  telugu: { en: 'Telugu', fr: 'Telugu' },
  turkish: { en: 'Turkish', fr: 'Turc' },
  tamil: { en: 'Tamil', fr: 'Tamoul' },
  cantonese: { en: 'Cantonese', fr: 'Cantonais' },
  vietnamese: { en: 'Vietnamese', fr: 'Vietnamien' },
};

export const ACCENT_FLAGS: Record<AccentType, string> = {
  american: '🇺🇸',
  british: '🇬🇧',
  australian: '🇦🇺',
  canadian: '🇨🇦',
  irish: '🇮🇪',
  scottish: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  parisian: '🇫🇷',
  quebecois: '🇨🇦',
  belgian: '🇧🇪',
  swiss: '🇨🇭',
  spanish: '🇪🇸',
  latin: '🏛️',
  greek: '🇬🇷',
  mandarin: '🇨🇳',
  hindi: '🇮🇳',
  arabic: '🇸🇦',
  bengali: '🇧🇩',
  russian: '🇷🇺',
  portuguese: '🇵🇹',
  indonesian: '🇮🇩',
  urdu: '🇵🇰',
  german: '🇩🇪',
  japanese: '🇯🇵',
  'nigerian-pidgin': '🇳🇬',
  marathi: '🇮🇳',
  telugu: '🇮🇳',
  turkish: '🇹🇷',
  tamil: '🇮🇳',
  cantonese: '🇭🇰',
  vietnamese: '🇻🇳',
};

export const ACCENT_LANGUAGE_CODES: Record<AccentType, string> = {
  american: 'en-US',
  british: 'en-GB',
  australian: 'en-AU',
  canadian: 'en-CA',
  irish: 'en-IE',
  scottish: 'en-GB',
  parisian: 'fr-FR',
  quebecois: 'fr-CA',
  belgian: 'fr-BE',
  swiss: 'fr-CH',
  spanish: 'es-ES',
  latin: 'la',
  greek: 'el-GR',
  mandarin: 'zh-CN',
  hindi: 'hi-IN',
  arabic: 'ar-SA',
  bengali: 'bn-BD',
  russian: 'ru-RU',
  portuguese: 'pt-PT',
  indonesian: 'id-ID',
  urdu: 'ur-PK',
  german: 'de-DE',
  japanese: 'ja-JP',
  'nigerian-pidgin': 'en-NG',
  marathi: 'mr-IN',
  telugu: 'te-IN',
  turkish: 'tr-TR',
  tamil: 'ta-IN',
  cantonese: 'yue-HK',
  vietnamese: 'vi-VN',
};
