import { AccentType } from './accents';

export type LearningLanguageConfig = {
  id: string;
  code: string;
  exportSuffix: string;
  flag: string;
  nameEn: string;
  nameFr: string;
  accent: AccentType;
  bcp47: string;
};

export const LEARNING_LANGUAGES = [
  {
    id: 'english',
    code: 'en',
    exportSuffix: 'En',
    flag: '🇬🇧',
    nameEn: 'English',
    nameFr: 'Anglais',
    accent: 'american',
    bcp47: 'en-US',
  },
  {
    id: 'french',
    code: 'fr',
    exportSuffix: 'Fr',
    flag: '🇫🇷',
    nameEn: 'French',
    nameFr: 'Français',
    accent: 'parisian',
    bcp47: 'fr-FR',
  },
  {
    id: 'spanish',
    code: 'es',
    exportSuffix: 'Es',
    flag: '🇪🇸',
    nameEn: 'Spanish',
    nameFr: 'Espagnol',
    accent: 'spanish',
    bcp47: 'es-ES',
  },
  {
    id: 'latin',
    code: 'la',
    exportSuffix: 'La',
    flag: '🏛️',
    nameEn: 'Latin',
    nameFr: 'Latin',
    accent: 'latin',
    bcp47: 'la',
  },
  {
    id: 'greek',
    code: 'el',
    exportSuffix: 'El',
    flag: '🇬🇷',
    nameEn: 'Greek',
    nameFr: 'Grec',
    accent: 'greek',
    bcp47: 'el-GR',
  },
  {
    id: 'mandarin',
    code: 'zh',
    exportSuffix: 'Zh',
    flag: '🇨🇳',
    nameEn: 'Mandarin Chinese',
    nameFr: 'Chinois mandarin',
    accent: 'mandarin',
    bcp47: 'zh-CN',
  },
  {
    id: 'hindi',
    code: 'hi',
    exportSuffix: 'Hi',
    flag: '🇮🇳',
    nameEn: 'Hindi',
    nameFr: 'Hindi',
    accent: 'hindi',
    bcp47: 'hi-IN',
  },
  {
    id: 'arabic',
    code: 'ar',
    exportSuffix: 'Ar',
    flag: '🇸🇦',
    nameEn: 'Standard Arabic',
    nameFr: 'Arabe standard',
    accent: 'arabic',
    bcp47: 'ar-SA',
  },
  {
    id: 'bengali',
    code: 'bn',
    exportSuffix: 'Bn',
    flag: '🇧🇩',
    nameEn: 'Bengali',
    nameFr: 'Bengali',
    accent: 'bengali',
    bcp47: 'bn-BD',
  },
  {
    id: 'russian',
    code: 'ru',
    exportSuffix: 'Ru',
    flag: '🇷🇺',
    nameEn: 'Russian',
    nameFr: 'Russe',
    accent: 'russian',
    bcp47: 'ru-RU',
  },
  {
    id: 'portuguese',
    code: 'pt',
    exportSuffix: 'Pt',
    flag: '🇵🇹',
    nameEn: 'Portuguese',
    nameFr: 'Portugais',
    accent: 'portuguese',
    bcp47: 'pt-PT',
  },
  {
    id: 'indonesian',
    code: 'id',
    exportSuffix: 'Id',
    flag: '🇮🇩',
    nameEn: 'Indonesian',
    nameFr: 'Indonésien',
    accent: 'indonesian',
    bcp47: 'id-ID',
  },
  {
    id: 'urdu',
    code: 'ur',
    exportSuffix: 'Ur',
    flag: '🇵🇰',
    nameEn: 'Urdu',
    nameFr: 'Ourdou',
    accent: 'urdu',
    bcp47: 'ur-PK',
  },
  {
    id: 'german',
    code: 'de',
    exportSuffix: 'De',
    flag: '🇩🇪',
    nameEn: 'German',
    nameFr: 'Allemand',
    accent: 'german',
    bcp47: 'de-DE',
  },
  {
    id: 'japanese',
    code: 'ja',
    exportSuffix: 'Ja',
    flag: '🇯🇵',
    nameEn: 'Japanese',
    nameFr: 'Japonais',
    accent: 'japanese',
    bcp47: 'ja-JP',
  },
  {
    id: 'nigerian-pidgin',
    code: 'pcm',
    exportSuffix: 'Pcm',
    flag: '🇳🇬',
    nameEn: 'Nigerian Pidgin',
    nameFr: 'Pidgin nigérian',
    accent: 'nigerian-pidgin',
    bcp47: 'en-NG',
  },
  {
    id: 'marathi',
    code: 'mr',
    exportSuffix: 'Mr',
    flag: '🇮🇳',
    nameEn: 'Marathi',
    nameFr: 'Marathi',
    accent: 'marathi',
    bcp47: 'mr-IN',
  },
  {
    id: 'telugu',
    code: 'te',
    exportSuffix: 'Te',
    flag: '🇮🇳',
    nameEn: 'Telugu',
    nameFr: 'Telugu',
    accent: 'telugu',
    bcp47: 'te-IN',
  },
  {
    id: 'turkish',
    code: 'tr',
    exportSuffix: 'Tr',
    flag: '🇹🇷',
    nameEn: 'Turkish',
    nameFr: 'Turc',
    accent: 'turkish',
    bcp47: 'tr-TR',
  },
  {
    id: 'tamil',
    code: 'ta',
    exportSuffix: 'Ta',
    flag: '🇮🇳',
    nameEn: 'Tamil',
    nameFr: 'Tamoul',
    accent: 'tamil',
    bcp47: 'ta-IN',
  },
  {
    id: 'cantonese',
    code: 'yue',
    exportSuffix: 'Yue',
    flag: '🇭🇰',
    nameEn: 'Cantonese',
    nameFr: 'Cantonais',
    accent: 'cantonese',
    bcp47: 'yue-HK',
  },
  {
    id: 'vietnamese',
    code: 'vi',
    exportSuffix: 'Vi',
    flag: '🇻🇳',
    nameEn: 'Vietnamese',
    nameFr: 'Vietnamien',
    accent: 'vietnamese',
    bcp47: 'vi-VN',
  },
] as const satisfies readonly LearningLanguageConfig[];

export const UI_LANGUAGES = [
  { id: 'en', flag: '🇺🇸', label: 'English' },
  { id: 'fr', flag: '🇫🇷', label: 'Français' },
] as const;
